# Generated by Django 4.2.6 on 2023-12-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_employee_id_employee_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
